In [10]:
import numpy as np
print(np.__version__)

1.21.5


In [ ]:
import numpy as np

l = [12.23, 13.32, 100, 36.32]

print("Original List:", l)

a = np.array(l)

print("One-dimensional NumPy array: ", a)

In [11]:
import numpy as np

x = np.arange(2, 11).reshape(3, 3)

print(x)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [14]:
import numpy as np

x=np.zeros(10)
print(x)

print("updated adter 8th value")
x[8]=9

print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
updated adter 8th value
[0. 0. 0. 0. 0. 0. 0. 0. 9. 0.]


In [16]:
import numpy as np

x=np.arange(50,100)
print(x)

[50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73
 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97
 98 99]


In [19]:
import numpy as np

x=np.arange(1,50)

print("original array")
print(x)

print("reverse array")
x=x[::-1]
print(x)


original array
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49]
reverse array
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1]


In [20]:
import numpy as np

a = [1, 2, 3, 4]

print("Original array")
print(a)

x = np.asfarray(a)

print("Array converted to a float type:")
print(x) 


Original array
[1, 2, 3, 4]
Array converted to a float type:
[1. 2. 3. 4.]


In [21]:
import numpy as np

x = np.ones((5, 5))

print("Original array:")
print(x)

print("1 on the border and 0 inside in the array")
x[1:-1, 1:-1] = 0

print(x)

Original array:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
1 on the border and 0 inside in the array
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [22]:
import numpy as np

x = np.ones((3, 3))

print("Original array:")
print(x)

print("0 on the border and 1 inside in the array")
x = np.pad(x, pad_width=1, mode='constant', constant_values=0)

print(x)

Original array:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
0 on the border and 1 inside in the array
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [23]:
import numpy as np

x = np.ones((3, 3))

print("Original array:")
print(x)

print("0 on the border and 1 inside in the array")
x = np.pad(x, pad_width=1, mode='constant', constant_values=0)

print(x)

Original array:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
0 on the border and 1 inside in the array
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [9]:
import numpy as np

x=[10,20,30]

print("Original Array")
print(x)

x=np.append(x,[[40,50,60],[70,80,90]])

print("after appending values")
print(x)

Original Array
[10, 20, 30]
after appending values
[10 20 30 40 50 60 70 80 90]


In [4]:
import numpy as np

my_list=[1,2,3,4,5,6,7,8]

print("list to array:")
print(np.asarray(my_list))

mytuple=([8,4,6],[1,2,3])

print("tuple to array")
print(np.asarray(mytuple))

list to array:
[1 2 3 4 5 6 7 8]
tuple to array
[[8 4 6]
 [1 2 3]]
